import { CharacterProfile, Item, GachaConfig, GachaReward } from "./types";

export const INITIAL_CHARACTERS: CharacterProfile[] = [
  {
    id: "yeon-chaewon",
    role: "player",
    username: "chaewon",
    displayName: "ยอน แชวอน (Yeon Chae-won)",
    nickname: "กลีบบัววิบัติ / นางแอ่นสวรรค์",
    avatarUrl: "/avatars/chaewon.svg",
    quote: "หากสายลมและเรื่องเล่ายังคงอยู่ ข้าจะกวัดแกว่งร่มคันนี้เพื่อทะลวงโชคชะตา",
    age: "อายุ 27 ปี",
    constellation: "สายลมหวนคืนสู่สวรรค์",
    characteristics: [
      "สุขุมและเยือกเย็น",
      "ผู้เชี่ยวชาญร่มศึกโบราณ",
      "จิตใจมั่นคงดุจศิลา",
      "เจ้าของเรื่องเล่าระดับมายา",
      "ผู้พิทักษ์สายใยแห่งสตรีม"
    ],
    storySummary: "เรื่องเล่าระดับกึ่งมายา: ผู้ผ่านพ้นบททดสอบแห่งร่มพายุและสายลมหยก",
    statusBuffs: "บัฟสายลมศักดิ์สิทธิ์ (Stack) - ความเร็วพุ่งทะยาน +15% และต้านทานสถานะผิดปกติ",
    coins: 6500,
    hp: 52,
    maxHp: 52,
    statUpgradeCount: 0,
    stats: {
      strength: 35,
      durability: 40,
      agility: 20,
      magic: 28,
    },
    skills: [
      {
        id: "skill-c-1",
        name: "ระบำร่มพิรุณโปรยปราย",
        level: 3,
        multiplier: 1,
        type: "วิชาประจำตัว",
        category: "stigma",
        orvRank: "legendary",
        description: "กางร่มสร้างเกราะสะท้อนพลังโจมตี 35% พร้อมปล่อยเข็มปราณลมตัดผ่าศัตรูรอบทิศ",
        conditions: "ใช้พลังเวท 35 หน่วย",
        perkLevel10: "เพิ่มอัตราสะท้อนเป็น 50% และฟื้นฟูเลือดอัตโนมัติ",
      },
      {
        id: "skill-c-2",
        name: "เพลงเตะนางแอ่นเหิน",
        level: 4,
        multiplier: 1,
        type: "วิชาต่อสู้ประชิด",
        category: "stigma",
        orvRank: "semi_myth",
        description: "กระโดดเหยียบอากาศสร้างคลื่นลมกระแทกศัตรูให้เสียจังหวะ",
      },
      {
        id: "skill-c-3",
        name: "ก้าวพริบตาแห่งสายลม",
        level: 4,
        multiplier: 1,
        type: "วิชาตัวเบา",
        category: "general",
        orvRank: "hero",
        description: "เคลื่อนที่ว่องไวดุจสายลม หลบหลีกการโจมตีทางกายภาพ",
        cooldown: "1 เทิร์น",
      },
      {
        id: "skill-c-4",
        name: "ม่านพลังบัวพิสุทธิ์",
        level: 4,
        multiplier: 1,
        type: "บัฟเสริมพลัง",
        category: "general",
        orvRank: "legendary",
        description: "ฟื้นฟู HP ทันที 20% และลดดาเมจที่ได้รับลงครึ่งหนึ่งเป็นเวลา 2 เทิร์น",
        cooldown: "3 เทิร์น",
      },
      {
        id: "skill-c-8",
        name: "พายุหมุนเก้าชั้นฟ้า (Ultimate)",
        level: 4,
        multiplier: 1,
        type: "Ultimate Skill",
        category: "story",
        orvRank: "myth",
        description: "ปลดปล่อยพลังมหาศาลแห่งสายลมทำลายล้างเป้าหมายทั้งหมดรอบตัวอย่างรุนแรง",
        cooldown: "5 เทิร์น",
        perkLevel10: "ดาเมจรุนแรงขึ้นสองเท่าและทำให้ศัตรูติดสถานะมึนงงสมบูรณ์",
      }
    ],
    inventory: [
      {
        id: "item-umbrella",
        instanceId: "inst-1",
        name: "ร่มเหล็กสายลมหยก",
        price: 300,
        description: "ร่มโบราณเสริมโครงเหล็กกล้าแกร่งทนทาน เสริมพลังสกิลระบำร่ม",
        category: "equipment",
        effectType: "enhance_skill",
        skillEnhanceTarget: "ระบำร่มพิรุณโปรยปราย",
        skillEnhanceDesc: "พลังสะท้อน +10%",
        usableByPlayers: true,
        isEquipped: true,
        quantity: 1,
      },
      {
        id: "item-fan",
        instanceId: "inst-2",
        name: "พัดขนนกวายุสวรรค์",
        price: 750,
        description: "พัดอาคมที่รวบรวมลมปราณธรรมชาติ",
        category: "equipment",
        effectType: "buff_stat",
        targetStat: "agility",
        effectValue: 10,
        usableByPlayers: true,
        isEquipped: true,
        quantity: 1,
      }
    ],
    quests: [
      {
        id: "q-1",
        title: "ผ่านด่านศึกดวลไพ่ 21 ชนะ 3 ครั้ง",
        description: "เข้าร่วมประลองในโหมดดวลไพ่ 21 และคว้าชัยชนะ",
        targetCount: 3,
        currentCount: 1,
        rewardCoins: 1500,
        rewardItemName: "ยาฟื้นพลังชีวิตชั้นยอด",
        isCompleted: false,
        isClaimed: false,
        createdAt: Date.now() - 3600000,
      }
    ],
    notifications: [
      {
        id: "notif-1",
        title: "[ระบบ] ยินดีต้อนรับสู่ Star Stream System",
        message: "ระบบลงทะเบียนสเตตัสและคลังกระเป๋าสำเร็จ ขอให้ท่านโชคดีในการเผชิญหน้ากับซีนาริโอ",
        timestamp: Date.now() - 7200000,
        read: false,
        type: "system",
      }
    ],
    powerScore: 8420,
    lastUpdated: Date.now(),
  },
  {
    id: "baek-hayeon",
    role: "admin",
    username: "hayeon",
    displayName: "แพ็ค ฮายอน (Baek Ha-yeon)",
    nickname: "โทแกบีผู้คุมกฎแห่งสตรีม / มารสวรรค์นิรันดร์",
    avatarUrl: "/avatars/hayeon.svg",
    quote: "ในโลกนี้ ผู้ที่กุมเรื่องเล่าและเหรียญตรา คือผู้ที่กำหนดชะตากรรมของจักรวาล",
    age: "อายุ 23 ปี",
    constellation: "ราชาอสูรผู้เฝ้ามองความว่างเปล่า",
    characteristics: [
      "ผู้ดูแลระบบสูงสุด (Admin)",
      "เนตรหยั่งรู้อนาคต",
      "เจ้าของเรื่องเล่าระดับตำนาน",
      "ผู้บงการตู้กาชาและร้านค้าดวงดาว",
      "ผู้คุมกฎแห่งศึกดวลไพ่"
    ],
    storySummary: "เรื่องเล่าระดับตำนาน: ผู้ข้ามผ่านวงล้อกาลเวลาและคุมกฎดวงดาว",
    statusBuffs: "ออร่าผู้คุมระบบ: พลังโจมตีและต้านทานดาเมจ +40%",
    coins: 25000,
    hp: 60,
    maxHp: 60,
    statUpgradeCount: 0,
    stats: {
      strength: 40,
      durability: 45,
      agility: 38,
      magic: 45,
    },
    skills: [
      {
        id: "skill-h-1",
        name: "คำสั่งผู้คุมกฎแห่งสตรีม",
        level: 5,
        multiplier: 1,
        type: "วิชาบงการระบบ",
        category: "stigma",
        orvRank: "myth",
        description: "ควบคุมและปรับเปลี่ยนกฎแห่งซีนาริโอ สั่งการเสกและลบพลังได้ตามบัญชา",
        perkLevel10: "อัตราสำเร็จ 100% ไม่มีเงื่อนไขขัดขวาง",
      },
      {
        id: "skill-h-2",
        name: "Tear of The Fool",
        level: 3,
        multiplier: 1,
        type: "วิชาประจำตัว",
        category: "innate",
        orvRank: "legendary",
        description: "ส่องแสงอาคมทะลวงบาเรียและสร้างความเสียหายรุนแรง",
      },
      {
        id: "skill-h-3",
        name: "Time Reversion (ย้อนเวลา)",
        level: 2,
        multiplier: 1,
        type: "เรื่องเล่ายักษ์",
        category: "story",
        orvRank: "myth",
        description: "ย้อนสถานะเวลาในพื้นที่เป้าหมาย 3 วินาที ลบล้างดาเมจที่เพิ่งเกิดขึ้น",
      }
    ],
    inventory: [
      {
        id: "item-coat",
        instanceId: "inst-h1",
        name: "เสื้อคลุมมิติอสูรทมิฬ",
        price: 1200,
        description: "เสื้อโค้ตโบราณที่ถักทอจากเศษเสี้ยวความมืด เสริมความทนทาน",
        category: "equipment",
        effectType: "buff_stat",
        targetStat: "durability",
        effectValue: 20,
        usableByPlayers: true,
        isEquipped: true,
        quantity: 1,
      }
    ],
    quests: [],
    notifications: [],
    powerScore: 12500,
    lastUpdated: Date.now(),
  },
  {
    id: "chayathat-chathai",
    role: "player",
    username: "chathai",
    displayName: "ชยาธัช ชาไทย (Chayathat)",
    nickname: "หมัดเพลิงสุริยัน",
    avatarUrl: "/avatars/sera.svg",
    quote: "หมัดเดียวเพื่อทะลวงทุกอุปสรรค!",
    age: "อายุ 19 ปี",
    constellation: "ราชสีห์เพลิงผู้ไร้พ่าย",
    characteristics: [
      "เลือดร้อนรักความยุติธรรม",
      "สายประชิดไร้เทียมทาน",
      "เพื่อนแท้แห่งสนามรบ"
    ],
    storySummary: "เรื่องเล่าระดับวีรชน: หมัดปราบสัตว์ร้ายในบททดสอบแรก",
    statusBuffs: "เพลิงคลั่ง: ดาเมจกายภาพ +20%",
    coins: 4500,
    hp: 35,
    maxHp: 35,
    statUpgradeCount: 0,
    stats: {
      strength: 25,
      durability: 20,
      agility: 22,
      magic: 15,
    },
    skills: [
      {
        id: "skill-ch-1",
        name: "หมัดสุริยันสะท้านปฐพี",
        level: 2,
        multiplier: 1,
        type: "กระบวนท่าประชิด",
        category: "general",
        orvRank: "hero",
        description: "ชกหมัดห่อหุ้มเปลวเพลิงระเบิดใส่เป้าหมาย",
      }
    ],
    inventory: [
      {
        id: "item-hammer",
        instanceId: "inst-ch1",
        name: "สนับมือศิลาเพลิง",
        price: 900,
        description: "สนับมือหุ้มเกราะศิลาเปลวเพลิง เสริมพลังหมัด",
        category: "equipment",
        effectType: "buff_stat",
        targetStat: "strength",
        effectValue: 8,
        usableByPlayers: true,
        isEquipped: true,
        quantity: 1,
      }
    ],
    quests: [],
    notifications: [],
    powerScore: 3450,
    lastUpdated: Date.now(),
  },
  {
    id: "revadis-ravencroft",
    role: "player",
    username: "revadis",
    displayName: "เรวาดิส (Revadis Ravencroft)",
    nickname: "เหยี่ยวราตรีแห่งเงา",
    avatarUrl: "/avatars/miyeon.svg",
    quote: "ความเงียบคืออาวุธที่คมกริบที่สุดในความมืด",
    age: "อายุ 26 ปี",
    constellation: "กาเหว่าเงาแห่งมิติมืด",
    characteristics: [
      "มือสังหารเงียบ",
      "มองเห็นจุดตาย",
      "มีสัมผัสที่หกแม่นยำ"
    ],
    storySummary: "เรื่องเล่าระดับกึ่งตำนาน: ผู้ลอบผ่านหมอกมรณะโดยไร้รอยขีดข่วน",
    statusBuffs: "อำพรางเงา: เพิ่มอัตราคริติคอล +25%",
    coins: 4000,
    hp: 32,
    maxHp: 32,
    statUpgradeCount: 0,
    stats: {
      strength: 18,
      durability: 16,
      agility: 28,
      magic: 22,
    },
    skills: [
      {
        id: "skill-r-1",
        name: "ก้าวเงาไร้สำเนียง",
        level: 2,
        multiplier: 1,
        type: "วิชาลอบเร้น",
        category: "innate",
        orvRank: "hero",
        description: "กลืนร่างไปกับความมืด เคลื่อนไหวไร้ร่องรอยและเสียงฝีเท้า",
      }
    ],
    inventory: [],
    quests: [],
    notifications: [],
    powerScore: 4100,
    lastUpdated: Date.now(),
  }
];

export const INITIAL_SHOP_ITEMS: Item[] = [
  {
    id: "shop-elixir-hp",
    name: "น้ำยาฟื้นฟูพลังชีวิต (Healing Potion)",
    price: 150,
    description: "ฟื้นฟูพลังชีวิต +10 HP ทันทีเมื่อกดใช้งาน",
    category: "consumable",
    icon: "HeartPulse",
    effectType: "heal_hp",
    effectValue: 10,
    hpBonus: 10,
    usableByPlayers: true,
    rarity: "common",
  },
  {
    id: "shop-lotus-snow",
    name: "สมุนไพรบัวหิมะพันปี (Snow Lotus)",
    price: 450,
    description: "สุดยอดสมุนไพรสวรรค์ ฟื้นฟูบาดแผลสาหัส ฟื้นฟูเลือด HP +20 หน่วยทันที",
    category: "consumable",
    icon: "Flower2",
    effectType: "heal_hp",
    effectValue: 20,
    hpBonus: 20,
    usableByPlayers: true,
    rarity: "rare",
  },
  {
    id: "shop-celestial-dew",
    name: "น้ำทิพย์ชำระกายาวิญญาณ (Celestial Cleansing Dew)",
    price: 300,
    description: "น้ำทิพย์บริสุทธิ์จากหุบเขาดวงดาว ฟื้นฟูเลือด HP +15 หน่วยทันที",
    category: "consumable",
    icon: "Droplets",
    effectType: "heal_hp",
    effectValue: 15,
    hpBonus: 15,
    usableByPlayers: true,
    rarity: "rare",
  },
  {
    id: "shop-elixir-maxhp",
    name: "น้ำยาโอสถทองคำ (Vitality Elixir)",
    price: 1500,
    description: "ขยายค่าพลังชีวิตสูงสุดถาวร (Max HP) +5 หน่วยอย่างถาวร",
    category: "consumable",
    icon: "Heart",
    effectType: "boost_max_hp",
    effectValue: 5,
    hpBonus: 5,
    usableByPlayers: true,
    rarity: "rare",
  },
  {
    id: "shop-blood-demon",
    name: "หยาดโลหิตราชันอสูร (Demon King's Vital Blood)",
    price: 1900,
    description: "แก่นโลหิตบรรพกาล เสริมโครงสร้างร่างกายถาวร ขยาย Max HP +6 หน่วยถาวร และฟื้นเลือด +6 HP",
    category: "consumable",
    icon: "Flame",
    effectType: "boost_max_hp",
    effectValue: 6,
    hpBonus: 6,
    usableByPlayers: true,
    rarity: "epic",
  },
  {
    id: "shop-golden-pulse-elixir",
    name: "โอสถทองคำทะลวงชีพจร (Golden Pulse Elixir)",
    price: 3500,
    description: "โอสถทิพย์ระดับตำนานที่โทแกบีนำเข้ามา ขยาย Max HP สูงสุดถาวร +10 หน่วย",
    category: "consumable",
    icon: "Sparkles",
    effectType: "boost_max_hp",
    effectValue: 10,
    hpBonus: 10,
    usableByPlayers: true,
    rarity: "legendary",
  },
  {
    id: "shop-dragon-armor",
    name: "เกราะอกเกล็ดมังกรนิล (Dragon Scale Armor)",
    price: 2800,
    description: "ชุดเกราะตีจากเกล็ดมังกรโบราณ เพิ่มความทนทาน +8 และมอบโบนัส Max HP +8 หน่วยเมื่อสวมใส่",
    category: "equipment",
    icon: "Shield",
    effectType: "buff_stat",
    targetStat: "durability",
    effectValue: 8,
    hpBonus: 8,
    usableByPlayers: true,
    rarity: "epic",
  },
  {
    id: "shop-ruby-heart-amulet",
    name: "สร้อยคอทับทิมชีพจร (Ruby Heart Amulet)",
    price: 1700,
    description: "สร้อยคอศิลาทับทิม มอบโบนัส Max HP +6 หน่วย และความทนทาน +4 เมื่อสวมใส่",
    category: "equipment",
    icon: "Heart",
    effectType: "buff_stat",
    targetStat: "durability",
    effectValue: 4,
    hpBonus: 6,
    usableByPlayers: true,
    rarity: "rare",
  },
  {
    id: "shop-crystal-strength",
    name: "ผลึกพลังกายาไททัน",
    price: 1200,
    description: "เพิ่มพละกำลัง (Strength) +5 หน่วยถาวร (ช่วยเพิ่ม Max HP ผ่านสูตร Base HP)",
    category: "consumable",
    icon: "ShieldAlert",
    effectType: "buff_stat",
    targetStat: "strength",
    effectValue: 5,
    usableByPlayers: true,
    rarity: "rare",
  },
  {
    id: "shop-crystal-magic",
    name: "ผลึกมานาแห่งดาวฤกษ์",
    price: 1200,
    description: "เพิ่มพลังเวท (Magic) +5 หน่วยถาวร",
    category: "consumable",
    icon: "Sparkles",
    effectType: "buff_stat",
    targetStat: "magic",
    effectValue: 5,
    usableByPlayers: true,
    rarity: "rare",
  },
  {
    id: "shop-equip-blade",
    name: "ดาบแสงดาวประกายฟ้า (Starlight Saber)",
    price: 2500,
    description: "ดาบที่ส่องแสงระยิบระยับ เพิ่มพลังโจมตีและความเร็ว",
    category: "equipment",
    icon: "Sword",
    effectType: "buff_stat",
    targetStat: "strength",
    effectValue: 12,
    usableByPlayers: true,
    rarity: "epic",
  },
  {
    id: "shop-equip-cloak",
    name: "ผ้าคลุมรัตติกาลดวงดาว",
    price: 1800,
    description: "ผ้าคลุมป้องกันความเสียหาย เพิ่มความทนทาน +10",
    category: "equipment",
    icon: "Shield",
    effectType: "buff_stat",
    targetStat: "durability",
    effectValue: 10,
    usableByPlayers: true,
    rarity: "rare",
  },
  {
    id: "shop-equip-flower-ring",
    name: "แหวนบุปผาสวรรค์บรรพกาล",
    price: 3500,
    description: "แหวนอาคมชั้นสูง เสริมพลังเวทและความเร็ว",
    category: "equipment",
    icon: "Flower2",
    effectType: "buff_stat",
    targetStat: "magic",
    effectValue: 15,
    usableByPlayers: true,
    rarity: "legendary",
  },
];

export const INITIAL_GACHA_CONFIG: GachaConfig = {
  pullCost: 500,
  tenPullCost: 4500,
  enabled: true,
  bannerTitle: "หีบสมบัติจักรวาลแห่งดวงดาว (Constellation Star Box)",
  bannerDescription: "สุ่มรับเหรียญรางวัลมหาศาล สกิลพิเศษระดับตำนาน และไอเทมสเตตัสหายาก",
};

export const INITIAL_GACHA_REWARDS: GachaReward[] = [
  {
    id: "gacha-coin-jackpot",
    name: "มหาสมบัติ 20,000 Coins (Jackpot)",
    type: "coin",
    rate: 3,
    rarity: "mythic",
    description: "รับเหรียญ 20,000 Coins ทันที",
    coinAmount: 20000,
  },
  {
    id: "gacha-skill-ring",
    name: "สกิล: วงแหวนเทพสุริยันต์นิรันดร์",
    type: "skill",
    rate: 4,
    rarity: "mythic",
    description: "สกิลบัฟระดับตำนาน เพิ่มสเตตัสทุกค่า 20% ในสนามรบ",
    skillData: {
      id: "skill-gacha-ring",
      name: "วงแหวนเทพสุริยันต์นิรันดร์",
      level: 3,
      multiplier: 2,
      type: "วิชาเทพดวงดาว",
      category: "stigma",
      orvRank: "myth",
      description: "ปลดปล่อยวงแหวนสุริยะเผาผลาญศัตรูและเสริมสเตตัสตนเอง",
      perkLevel10: "พลังทำลายคูณ 3 เท่าและฟื้นฟูเลือดอัตโนมัติ",
    },
  },
  {
    id: "gacha-coin-gold",
    name: "หีบเหรียญทองคำ (6,000 Coins)",
    type: "coin",
    rate: 8,
    rarity: "legendary",
    description: "รับเหรียญ 6,000 Coins ทันที",
    coinAmount: 6000,
  },
  {
    id: "gacha-item-crown",
    name: "มงกุฎแห่งราชาดวงดาว",
    type: "item",
    rate: 7,
    rarity: "legendary",
    description: "อุปกรณ์สวมใส่ เสริมพลังเวท +25 หน่วย",
    itemData: {
      id: "item-gacha-crown",
      name: "มงกุฎแห่งราชาดวงดาว",
      price: 6000,
      description: "มงกุฎเกียรติยศ เสริมพลังเวทมหาศาล",
      category: "equipment",
      effectType: "buff_stat",
      targetStat: "magic",
      effectValue: 25,
      usableByPlayers: true,
      rarity: "legendary",
    },
  },
  {
    id: "gacha-skill-step",
    name: "สกิล: ก้าวล่องหนเก้าวิถี",
    type: "skill",
    rate: 12,
    rarity: "epic",
    description: "สกิลหลบหลีกและเคลื่อนที่ชั่วพริบตา",
    skillData: {
      id: "skill-gacha-step",
      name: "ก้าวล่องหนเก้าวิถี",
      level: 2,
      multiplier: 1,
      type: "วิชาตัวเบา",
      category: "general",
      orvRank: "semi_myth",
      description: "ก้าวหลบการโจมตีอย่างสมบูรณ์ 2 ครั้ง",
    },
  },
  {
    id: "gacha-item-elixir",
    name: "ยาปราณมังกรฟ้า (Dragon Elixir)",
    type: "item",
    rate: 14,
    rarity: "epic",
    description: "ยาฟื้นพลัง เพิ่มพละกำลัง +15 หน่วยถาวร",
    itemData: {
      id: "item-gacha-elixir",
      name: "ยาปราณมังกรฟ้า",
      price: 3500,
      description: "ยาโอสถระดับสูง เพิ่มค่าพละกำลัง",
      category: "consumable",
      effectType: "buff_stat",
      targetStat: "strength",
      effectValue: 15,
      usableByPlayers: true,
      rarity: "epic",
    },
  },
  {
    id: "gacha-coin-silver",
    name: "ถุงเหรียญเงิน (2,000 Coins)",
    type: "coin",
    rate: 22,
    rarity: "rare",
    description: "รับเหรียญ 2,000 Coins",
    coinAmount: 2000,
  },
  {
    id: "gacha-characteristic-starter",
    name: "คุณลักษณะ: ผู้ดูดาราเริ่มต้น",
    type: "characteristic",
    rate: 5,
    rarity: "common",
    description: "คุณลักษณะเริ่มต้นจากกลุ่มดาวผู้สนับสนุน",
    characteristic: "ผู้ดูดาราเริ่มต้น",
  },
  {
    id: "gacha-coin-copper",
    name: "เหรียญรางวัลดวงดาว (800 Coins)",
    type: "coin",
    rate: 30,
    rarity: "common",
    description: "รับเหรียญ 800 Coins",
    coinAmount: 800,
  },
];
